### ISSUE TITLE
Can someone help me understand what's going on in lib_enum?

### ISSUE THREAD

**Issue by mferrie** [KSP-KOS/KSLib#103]
I'm having a hard time understanding the code because it's been compressed so much. Not really an issue per se, but IDK where else to ask this question.

**Comment by TDW89** [comment]
Hi @mferrie have you found the documentation page for it? If you go to the /doc/ folder there is a `.md` file for each script in the library. [here](https://github.com/KSP-KOS/KSLib/blob/master/doc/lib_enum.md)
Are you having trouble following any bit of it in particular or the thing as a whole? If it's just the formatting that you're having trouble with I would suggest grabbing a copy of it and reformatting it to your preferred style for easier reading.
Hope that helps if not feel free to let me know and I will try to do a better job of explaining.

**Comment by gisikw** [comment]
Hiya - sorry it's heavily compressed. It's a fairly large suite of functions, so I wanted to make sure it was still viable for people on career with limited file size. That meant keeping line breaks, but largely minifying variable names.

**Comment by mferrie** [comment]
@gisikw *heavily edits to guess at restoring names that  make sense* Oh, I get it now! :D
