### ISSUE TITLE
Extend lib_lazcalc to handle north/south transitions during ascent

### ISSUE THREAD

**Issue by bfrobin446** [KSP-KOS/KSLib#104]
If you launch just north of due east from a launch site that's north of the equator (for instance, in RSS, launch from Cape Canaveral with a target inclination of 28.8 to 29 degrees), you'll pass your maximum latitude and curve back to the south before you finish your ascent. This can lead to an unpleasant surprise when your ground track is 093° but lib_lazcalc, still set on "launch at ascending node", wants to steer 087°.

If we can automatically update the initial north/south selection based on the vessel's current velocity, so that we switch to a southward azimuth when we start moving south, it will allow callers to reach these orbits by simply steering the azimuth that lib_lazcalc returns, just as they could with any other physically possible inclination.

**Comment by scimas** [comment]
Fixed by #105
