### ISSUE TITLE
improvments to lib_navball

### ISSUE THREAD

**Issue by nuggreat** [KSP-KOS/KSLib#121]
A person asking for help with getting the pitch and compass heading of a vector showed up in Dunbaratu's stream chat on 8/29 and was pointed at `lib_navball.ks`.  As said lib only works with the `vessel:facing` that proved not helpful because said person didn't know how to convert them to use a vector.  As a result it was the idea was floated that `lib_navball.ks` be changed to allow for any vector to be used.

**Comment by scimas** [comment]
Fixed by #122
