### ISSUE TITLE
rounding error in time_formatting from lib_num_to_formatted_str

### ISSUE THREAD

**Issue by beeryt** [KSP-KOS/KSLib#125]
It appears that seconds place rounding is truncated.
```
RUNPATH("/path/to/lib_num_to_formatted_str").
LOCAL value IS 0.999.
PRINT time_formatting(value, 3, 2, TRUE).  // T+ 00.99    should be T+ 01.00
PRINT time_formatting(value, 3, 1, TRUE).  // T+ 00.9     should be T+ 01.0
PRINT time_formatting(value, 3, 0, TRUE).  // T+ 00       should be T+ 01
```

**Comment by nuggreat** [comment]
Not a bug the use fact the function is flooring the values is intentional as without using floor I was seeing errors when formatting values like `59.999` as that would result in `0:60.00` and I didn't like that so I made the decision to floor as apposed to round.
