### ISSUE TITLE
• Game_of_Ur

### ISSUE THREAD

**Issue by Zyt3x** [KSP-KOS/KSLib#139]
Did you seriously create Chess in Kerbal Space Program??

That's wild.

Try integrating a One-Player Zug-Zwang and see if you can tell the solution to break the chaotic inference :)

**Comment by Zyt3x** [comment]
nuggreat; Have you read the sourcecode?

**Comment by nuggreat** [comment]
That reads like a pile of nonsense for a  few reason.  Most notably that Babylonia is in Mesopotamia and that everything I can quickly find on the history of chess says that chess originates in India not Mesopotamia.  Also that fact I was unable to find anything under the name "Game of Ur" that didn't simply point at what I implemented.

So regardless I an closing this as not relevant to KSlib.
