### ISSUE TITLE
Parameter "r" for multiple functions breaks dev kOS version

### ISSUE THREAD

**Issue by darthgently** [KSP-KOS/KSLib#145]
I only bring it up because it should be a problem given R is reserved for rotations, and if nothing changes next kOS release could break the library and any others using "r" as a user identifier. 
This was detected in lib_enum, not sure if a wider issue

**Comment by darthgently** [comment]
Temp workaround, change parm to "rr" in all occurrences of local copy of lib_enum

**Comment by nuggreat** [comment]
Fixed by PR#146
