### ISSUE TITLE
Improve example_lib_lazcalc

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#38]
It is not clear for the end user that examle_lib_lazcalc actually takes arguments because other examples don't take arguments. I know that the normal order is to look what you are about to run before running it but some users (including me) might start by looking at what it does because currently most of the examples in KSLib currently only print something on the screen. I'd recommend using a hardcoded list of desired orbits instead and printing something like this:
```
Altitude: 80000 m Inclination: 0 deg Azimuth: ...
Altitude: 100000 m Inclination: 45 deg Azimuth: ...
Altitude: 500000 m Inclination: 85 deg Azimuth: ...
```
@space-is-hard What do you think?

**Comment by space-is-hard** [comment]
Makes sense. I wasn't really sure what to do for an example.
