### ISSUE TITLE
lib_ag_list_dialog needs to be redone

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#41]
reasons:
1. It has too complex interface on the code side
2. Menu dialog is now in a separate library. It makes sense. So I'm going to remove it from lib_ag_list_dialog

What do I want to do:
1. remove menu_dialog
2. simplify list_dialog's to just accept title ant list and use hardcoded action group numbers
3. rename library to "lib_list_dialog" because now it has no action groups in it's code-side interface and it may be redone to the other way of getting user input without breaking anything.

**Comment by abenkovskii** [comment]
Alternatively I can just make a new library without removing the old one.

**Comment by abenkovskii** [comment]
Ready. Waiting confirmation.

**Comment by TDW89** [comment]
this is merged. closing issue
