### ISSUE TITLE
PID_seek interface is counter intuitive

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#42]
Why it doesn't clamp the return value too? I'm new to PID and may be I'm misunderstanding something but I expected the return value to be clamped.

**Comment by Dunbaratu** [comment]
It *was* clamped at some point.  Something removed that along the way.

**Comment by abenkovskii** [comment]
Fixed. BTW hovercrafts capable of flying in low Kerbin atmosphere are now hard to make. Ended up using cheats because I'm lazy.
