### ISSUE TITLE
Warping to a specific time

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#46]
see this: https://github.com/KSP-KOS/KOS/issues/882
`warp_to` will need to take a custom display update function as an argument and call it every iteration. Likely we have such a powerful tool as lib_exec.

**Comment by akrasuski1** [comment]
Yeah, it will be pretty simple to do:
```
until time<warp_to_time{
   exec_whatever.
}
```

**Comment by TDW89** [comment]
Now supported by kOS
