### ISSUE TITLE
We need lib_gui_box

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#51]
I hate code duplication and we have the same code for printing cool-looking window in lib_number_dialog and in lib_menu

**Comment by TDW89** [comment]
probably best done as an addition to lib_term as that does circles and lines already

**Comment by abenkovskii** [comment]
HOWTO.md:
> 1. Try to break things up into smaller files. A person trying to load them onto their installation may be > trying to save space and want to only install those things they need.

What do you think?

**Comment by TDW89** [comment]
humm yep fair enough boxes are probably useful more often than the rest of that lib.  I was thinking of adding just a small function that used the line drawing already in lib_term but for boxes that are square to the terminal there is probably a bit of overhead with that. (would let you draw boxes at an angle tough.

**Comment by abenkovskii** [comment]
How I imagine it:
`function draw_box(top, left, w, h)`
`function draw_wide_box(top, h)`
What do you think about the second function? Do we need it or only one function is fine?

**Comment by TDW89** [comment]
the second one probably not so much but but one that you fed a %width and %height to might be useful.
also i was thinking of a style argument so that it could be used to print different boxes (eg for indicating focus of selection)

**Comment by abenkovskii** [comment]
I'd rather take 3 additional arguments (border_h, border_v, angle) than implementing a limited number of styles.

**Comment by TDW89** [comment]
that works too. how would you feel about the args `(list(y0,h,x0,w),list(horizontal,vertical,corner)` that way it is possible to detect what is has been passed so that `draw_box(list(1,5),list("#"))` could be used for a full width box where all the borders were `#`? or is that overcomplicating it?

**Comment by akrasuski1** [comment]
Maybe some function from this can be useful:
https://github.com/akrasuski1/akrOS/blob/master/lib_window.ks

**Comment by abenkovskii** [comment]
@TDW89 In python there are keyword arguments exactly for this purpose. I think taking lists of different size is too complicated. We can make wrapper functions instead.

**Comment by akrasuski1** [comment]
Yes, I agree with @abenkovskii - wrapper functions seem to be way to go in this case.

**Comment by abenkovskii** [comment]
I'm going to post a PR adding this soon.
