### ISSUE TITLE
Document changes in lib_exec, lib_list_dialog and lib_menu

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#52]
I don't know why but for some reason I hate doing documentation. I should probably do it though.
PRs with changes:
1. #37 - lib_exec
2. #49 [not merged yet] - lib_menu, lib_list_dialog

**Comment by abenkovskii** [comment]
@akrasuski1 Turns out that lib_manu is not documented at all. As well as lib_number_dialog.

**Comment by TDW89** [comment]
documentation added. closing issue
