### ISSUE TITLE
The file name "example_lib_term.png" confuses me every time I see it

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#57]
@Dunbaratu I think this .png file should be renamed.

**Comment by akrasuski1** [comment]
Yeah, I agree with this. We should either post images on separate sites, in separate folder, or at least name them something obvious - for example `image_lib_term.png`.

**Comment by abenkovskii** [comment]
Let's rename it.

**Comment by abenkovskii** [comment]
Not closing it in case someone has objections.

**Comment by TDW89** [comment]
It's been almost 2 months with no objections I will close this.
