### ISSUE TITLE
Example_lib_pid and KSP 1.0

### ISSUE THREAD

**Issue by abenkovskii** [KSP-KOS/KSLib#58]
Due to the new ISP system most hovercrafts (including the one from showcase video) are no longer capable of flying in low Kerbin atmosphere.
I think example_lib_pid should display a warning using `HUDTEXT` if twr is lesser than 1.

**Comment by space-is-hard** [comment]
Is it necessary? If the TWR is below 1 then the user will see full throttle and a stationary craft anyways.

**Comment by Dunbaratu** [comment]
I think it works fine if you just swap out the engine.  Change the LV-909 to a LV-T45.
