### ISSUE TITLE
Should we put some standard stripper utilities here?

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KSLib#6]
One thing I often do is run a "stripper" script that compacts all my kerboscript code into a form where all the comments and indenting space is removed.

It occurs to me that maybe either putting utility scripts here (they'd have to be OS-dependant to some extent) that do that for others may be nice, or even more ambitious still, we could make a tool that automatically does this with all submitted code and provides a "stripped" folder with the stripped versions.  Note, the original would be preserved as well.  This would be a second copy of the script.

It would be nice if people didn't feel constrained to have to write their scripts compactly just to reduce footprint, and instead could make them well indented and commented, especially as putting scripts here is meant to be a useful teaching tool as well as a library.

(while I'm at it - header comment detection and stripping to auto-gen MD document files could be pretty good too - but that should be a separate issue)

**Comment by austinjames314** [comment]
If the purpose is to have scripts that use less memory in-game, wouldn't it make more sense to just use .ksm files? I've not used them much, and am aware that they're apparently bigger in 0.17, but wouldn't it make sense to put any effort into making 'compiled' scripts smaller?

**Comment by abenkovskii** [comment]
@Dunbaratu It would also be nice to have a "merge scripts I choose into one big file" script. This will reduce the number of `copy` commands to upload a program onto a vessel. It also could automatically search for the dependencies (by searching an argument of run command in the library folder). Plus compiled version of this big file will take a slightly less space because some string constants will be reused.
@austinjames314 Yes the information about comments and indents isn't stored in .ksm files.

**Comment by Dunbaratu** [comment]
KSM is no longer a large reduction in space unless you use a lot of comments.  But it might be in the future.  I still have some optimizations I could do to the code here and there.

What I am quite interested in, however, is the idea of doing a small program that runs through and strips out doc-comments from the scripts, so you don't need to maintain BOTH a comment in the script describing the arguments, return ,and description of a function, AND repeat that info in the .md file.  It would be nice if we could do a thing similar to javadoc, or doxygen, or C#'s xml comments.

**Comment by Dunbaratu** [comment]
There's a part of me that wants to see if it's possible to fiddle with the compiler in kOS.Safe to make a separate command-line program that will parse the script and make the docs.. but that may be overkill when all it needs to do is read the comment tags and find the name at the start of the next function.

**Comment by abenkovskii** [comment]
Also: a small script that replaces all white space characters with spaces can considerably reduce the size of .ksm file produced by the compiler by reducing %D section to almost nothing.

**Comment by abenkovskii** [comment]
Problem: this small script will have to remove comments too so the task is a bit less easy.

**Comment by abenkovskii** [comment]
@Dunbaratu Does your implementation turn whole file into one long line?

**Comment by Dunbaratu** [comment]
No.  that would be horrible because then any reported errors would be impossible to find - the line number would be wrong.  line breaks are the only whitespace I keep, because I want the line number counts to still be right.

**Comment by abenkovskii** [comment]
@Dunbaratu I think there should be an optional "extreme compression". Removing line breaks doesn't make working with .ks easier but it reduces the size of .ksm.

**Comment by abenkovskii** [comment]
@Dunbaratu I think the stripper in the library might improve the code style by it making comments and indents cost nothing.

**Comment by Dunbaratu** [comment]
That's what I was thinking.  I see some people using one-space indents and I think the only reason they're doing that is code size.

I have really never liked this idea of making people pay for comment space.  Yes it's true that the old 60's computers only had a few K, but that space was taken up with low level machine code, not source code with indents and comments, in an object oriented system.

**Comment by abenkovskii** [comment]
1. @Dunbaratu 
> spit out the numerical bytes for the ML, and then WOVE those bit patterns into the rope memory by people following instructions on cards in front of them. (put wire A into slot 53, put wire B into slot 71, etc.)

.ksm sort of does what you said. Am I missing something important?
2. To be explicit: I vote for including stripper into the repo because an argument: "we have a stripper in our lib so add indent or I'll go mad" is much more powerful argument than "there is a stripper hidden somewhere on the internet so you'd better add the indent"
