### ISSUE TITLE
lib_pid should be changed to use new LIST() constructor

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-KOS/KSLib#7]
liib_pid.ks was written before you could pass arguments to the LIST() constructor.  So it has many places that make an empty list, then populate it one  LIST:ADD call a a time.

That's really inefficient now that there's the new LIST(a,b,c,,) constructor.  It could be changed to build the whole list in one go with the constructor and get it over with in far fewer opcode instructions.

**Comment by erendrake** [comment]
Goto bed :-)

**Comment by austinjames314** [comment]
I'm going to take a swing at this as my first time contributing to a project. Seems simple enough?..

**Comment by abenkovskii** [comment]
@austinjames314 's PR is #8
P.S. It's a good practice to add a link to the PR into issue.

**Comment by austinjames314** [comment]
Ahh, thanks @abenkovskii , that makes sense.
