### ISSUE TITLE
0.19 Compatability.

### ISSUE THREAD

**Issue by TDW89** [KSP-KOS/KSLib#99]
Quick fixes to make sure everything still works in 0.19 ( i will do a more in depth re-write of some stuff over the weekend).
- lib_exec broken. (has been for a while) No known fix, put notification.
  - lib_raw_user_input (might be able to work around this)
- spec_char.ksm no longer required, change scripts over to use `char()` add notification to the `.ksm`
  - (example_)lib_input_string
  - lib_gui_box
- lib_seven_seg restructure to take into account new string comparison.
- example_lib_running_average_filter contains incorrect reference to function.

feel free to add to this list with anything you find anyone

**Comment by scimas** [comment]
Closing as fixed in #116 and #117. @nuggreat may have a solution for `lib_exec.ks`.
